Sys.setlocale("LC_TIME", "en_US.UTF-8") 
data <- read.csv2("/Users/tiagoassano/Documents/household_power_consumption.txt", stringsAsFactors = FALSE)
data <- mutate(data, Complete_date = paste(Date, Time))
data$Time <- strptime(data$Time, format = "%T")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data$Complete_date <- strptime(data$Complete_date, format = "%d/%m/%Y %H:%M:%S")
data$Global_active_power <- as.numeric(data$Global_active_power)
data1<- subset(data,Date=="2007-02-01"| Date=="2007-02-02")
png(filename= "plot2.png" )
with(data1, plot(Complete_date, Global_active_power, type ="l", 
                 ylab = "Global Active Power (kilowatts)", xlab = ""))
dev.off()